// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WASD.QLicPlatform.API.Shared.Infrastructure.Persistence.EFC.Configuration;

#nullable disable

namespace WASD.QLicPlatform.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251128235258_UpdateReportSummariesDecimals")]
    partial class UpdateReportSummariesDecimals
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WASD.QLicPlatform.API.Alerts.Domain.Model.Aggregate.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Alert");
                });

            modelBuilder.Entity("WASD.QLicPlatform.API.Anomalies.Domain.Model.Aggregate.Anomaly", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("detected_at");

                    b.Property<string>("Metadata")
                        .HasColumnType("longtext")
                        .HasColumnName("metadata");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int")
                        .HasColumnName("profile_id");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("resolved_at");

                    b.Property<int>("Severity")
                        .HasColumnType("int")
                        .HasColumnName("severity");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("p_k_anomalies");

                    b.HasIndex("DetectedAt")
                        .HasDatabaseName("ix_anomalies_detected_at");

                    b.HasIndex("ProfileId", "Status")
                        .HasDatabaseName("ix_anomalies_profile_status");

                    b.ToTable("anomalies", (string)null);
                });

            modelBuilder.Entity("WASD.QLicPlatform.API.IAM.Domain.Model.Aggregates.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("WASD.QLicPlatform.API.Payments.Domain.Model.Aggregate.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date");

                    b.Property<int>("MethodId")
                        .HasColumnType("int")
                        .HasColumnName("method_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("p_k_payments");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("WASD.QLicPlatform.API.Payments.Domain.Model.Aggregates.BillingSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Autopay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("autopay");

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("monthly")
                        .HasColumnName("billing_cycle");

                    b.Property<bool>("EmailNotifications")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("email_notifications");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_update");

                    b.Property<int>("PreferredBillingDay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("preferred_billing_day");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_billing_settings");

                    b.ToTable("billing_settings", (string)null);
                });

            modelBuilder.Entity("WASD.QLicPlatform.API.Payments.Domain.Model.Aggregates.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("details");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("p_k_payment_methods");

                    b.ToTable("payment_methods", (string)null);
                });

            modelBuilder.Entity("WASD.QLicPlatform.API.Profiles.Domain.Model.Aggregates.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("Profile");
                });

            modelBuilder.Entity("WASD.QLicPlatform.API.Reports.Domain.Model.Aggregates.CostBreakdown", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("cost");

                    b.Property<long>("ReportSummaryId")
                        .HasColumnType("bigint")
                        .HasColumnName("report_summary_id");

                    b.HasKey("Id")
                        .HasName("p_k_report_summary_cost_breakdowns");

                    b.HasIndex("ReportSummaryId")
                        .HasDatabaseName("i_x_report_summary_cost_breakdowns_report_summary_id");

                    b.ToTable("report_summary_cost_breakdown", (string)null);
                });

            modelBuilder.Entity("WASD.QLicPlatform.API.Reports.Domain.Model.Aggregates.EfficiencyMetrics", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("CostSaved")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("cost_saved");

                    b.Property<long>("ReportSummaryId")
                        .HasColumnType("bigint")
                        .HasColumnName("report_summary_id");

                    b.Property<int>("Score")
                        .HasColumnType("int")
                        .HasColumnName("score");

                    b.Property<int>("WaterSaved")
                        .HasColumnType("int")
                        .HasColumnName("water_saved");

                    b.HasKey("Id")
                        .HasName("p_k_report_summary_efficiency_metrics");

                    b.HasIndex("ReportSummaryId")
                        .IsUnique()
                        .HasDatabaseName("i_x_report_summary_efficiency_metrics_report_summary_id");

                    b.ToTable("report_summary_efficiency_metrics", (string)null);
                });

            modelBuilder.Entity("WASD.QLicPlatform.API.Reports.Domain.Model.Aggregates.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_reports");

                    b.ToTable("reports", (string)null);
                });

            modelBuilder.Entity("WASD.QLicPlatform.API.Reports.Domain.Model.Aggregates.ReportSummary", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("location");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("period");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("resource");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("p_k_report_summaries");

                    b.ToTable("report_summaries", (string)null);
                });

            modelBuilder.Entity("WASD.QLicPlatform.API.Reports.Domain.Model.Aggregates.UsageTrend", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Day")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("day");

                    b.Property<int>("Liters")
                        .HasColumnType("int")
                        .HasColumnName("liters");

                    b.Property<long>("ReportSummaryId")
                        .HasColumnType("bigint")
                        .HasColumnName("report_summary_id");

                    b.HasKey("Id")
                        .HasName("p_k_report_summary_usage_trends");

                    b.HasIndex("ReportSummaryId")
                        .HasDatabaseName("i_x_report_summary_usage_trends_report_summary_id");

                    b.ToTable("report_summary_usage_trends", (string)null);
                });

            modelBuilder.Entity("WASD.QLicPlatform.API.Subscriptions.Domain.Model.Aggregates.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("plan");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("price");

                    b.HasKey("Id")
                        .HasName("p_k_subscriptions");

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("WASD.QLicPlatform.API.Usage_Management.Domain.Model.Aggregate.UsageEvents", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("UsageEvents");
                });

            modelBuilder.Entity("WASD.QLicPlatform.API.Usage_Management.Domain.Model.Aggregate.UsageSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Current")
                        .HasColumnType("int");

                    b.Property<int>("DailyLimit")
                        .HasColumnType("int");

                    b.Property<int>("MonthlyTotal")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UsageSummary");
                });

            modelBuilder.Entity("WASD.QLicPlatform.API.Profiles.Domain.Model.Aggregates.Profile", b =>
                {
                    b.OwnsOne("WASD.QLicPlatform.API.Profiles.Domain.Model.ValueObjects.EmailAddress", "Email", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("EmailAddress");

                            b1.HasKey("Id");

                            b1.ToTable("Profile");

                            b1.WithOwner()
                                .HasForeignKey("Id");
                        });

                    b.OwnsOne("WASD.QLicPlatform.API.Profiles.Domain.Model.ValueObjects.PersonName", "Name", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("FirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("LastName");

                            b1.HasKey("Id");

                            b1.ToTable("Profile");

                            b1.WithOwner()
                                .HasForeignKey("Id");
                        });

                    b.OwnsOne("WASD.QLicPlatform.API.Profiles.Domain.Model.ValueObjects.StreetAddress", "Address", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("AddressCity");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("AddressCountry");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("AddressNumber");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("AddressPostalCode");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("AddressStreet");

                            b1.HasKey("Id");

                            b1.ToTable("Profile");

                            b1.WithOwner()
                                .HasForeignKey("Id");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("WASD.QLicPlatform.API.Reports.Domain.Model.Aggregates.CostBreakdown", b =>
                {
                    b.HasOne("WASD.QLicPlatform.API.Reports.Domain.Model.Aggregates.ReportSummary", "ReportSummary")
                        .WithMany("CostBreakdown")
                        .HasForeignKey("ReportSummaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_costbreakdown_summary");

                    b.Navigation("ReportSummary");
                });

            modelBuilder.Entity("WASD.QLicPlatform.API.Reports.Domain.Model.Aggregates.EfficiencyMetrics", b =>
                {
                    b.HasOne("WASD.QLicPlatform.API.Reports.Domain.Model.Aggregates.ReportSummary", "ReportSummary")
                        .WithOne("EfficiencyMetrics")
                        .HasForeignKey("WASD.QLicPlatform.API.Reports.Domain.Model.Aggregates.EfficiencyMetrics", "ReportSummaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_efficiency_summary");

                    b.Navigation("ReportSummary");
                });

            modelBuilder.Entity("WASD.QLicPlatform.API.Reports.Domain.Model.Aggregates.UsageTrend", b =>
                {
                    b.HasOne("WASD.QLicPlatform.API.Reports.Domain.Model.Aggregates.ReportSummary", "ReportSummary")
                        .WithMany("UsageTrends")
                        .HasForeignKey("ReportSummaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usagetrend_summary");

                    b.Navigation("ReportSummary");
                });

            modelBuilder.Entity("WASD.QLicPlatform.API.Reports.Domain.Model.Aggregates.ReportSummary", b =>
                {
                    b.Navigation("CostBreakdown");

                    b.Navigation("EfficiencyMetrics");

                    b.Navigation("UsageTrends");
                });
#pragma warning restore 612, 618
        }
    }
}
